global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'java17'
    static_configs:
      - targets: ['app-java17:8081']
        labels:
          java_version: '17'
    metrics_path: '/actuator/prometheus'

  - job_name: 'java21'
    static_configs:
      - targets: ['app-java21:8082']
        labels:
          java_version: '21'
    metrics_path: '/actuator/prometheus'

  - job_name: 'java25'
    static_configs:
      - targets: ['app-java26:8083']
        labels:
          java_version: '25'
    metrics_path: '/actuator/prometheus'
