spring.application.name=java17
server.port=8081
management.endpoints.web.exposure.include=prometheus,health
management.endpoint.prometheus.access=unrestricted

management.metrics.distribution.percentiles-histogram.http.server.requests=true
