spring.application.name=java25
server.port=8083
management.endpoints.web.exposure.include=prometheus,health
management.endpoint.prometheus.access=unrestricted
spring.threads.virtual.enabled=true

management.metrics.distribution.percentiles-histogram.http.server.requests=true
